# Generated by Django 2.1.4 on 2020-03-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20200301_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='article_tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='article.ArticleTag'),
        ),
    ]
